version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 5
    reviewers:
      - 'barkbarkdev/redacted-frontend' # temp switch
    schedule:
      interval: 'daily'
      time: '04:20'
    target-branch: 'develop'
